version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    deploy:
      replicas: 1
  web:
    image: elixirelm/blorg:latest
    build: .
    command: mix phx.server
    volumes:
      - .:/usr/local/src/phoenix/myapp
    ports:
      - "4000:4000"
    depends_on:
      - db
