version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/vol/blorg-${MIX_ENV}/postgres/data:/var/lib/postgresql/data
    deploy:
      replicas: 1
  web:
    image: elixirelm/blorg:${APP_IMG_TAG}
    volumes:     #NO_prod#NO_local
      - .:/myapp #NO_prod#NO_local
    environment:
      - MIX_ENV=${APP_MIX_ENV}
      - PORT=4000
    command: mix phx.server
    ports:
      - "4000:4000" #NO_prod#NO_local
      - "80:4000"   #NO_dev
    depends_on:
      - db
