# Author: umur.ozkul@gmail.com
version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/vol/blorg-${APP_MIX_ENV}/postgres/data:/var/lib/postgresql/data
    deploy:
      replicas: 1
  web:
    image: elixirelm/blorg:${APP_IMAGE_TAG}
    volumes:     #NO_prod#NO_local
      - ..:/myapp #NO_prod#NO_local
    environment:
      - MIX_ENV=${APP_MIX_ENV}
      - PORT=${APP_PORT}
    command: mix phx.server #NO_dev
    command: tail -f /var/log/dmesg #NO_prod#NO_local
    ports:
      - "4101:4101" #NO_prod#NO_local
      - "8101:8101" #NO_dev
    depends_on:
      - db
